spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    activate:
      on-profile: prod

images-dir: ${IMAGES_DIR}
images-temp-dir: ${IMAGES_TEMP_DIR}
logging:
  level:
    root: INFO

api:
  image: https://${artx.host}/v1/images

artx:
  port: 8080
  host: api.stdout.site
